shallow_clone: true

platform:
  - x86
  # - x64

configuration:
  - Debug
  # - Release

image:
  - Visual Studio 2015
  # - Visual Studio 2017

cache:
  - C:\cmake-3.8.0-win32-x86

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: MD c:\logs\
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.8.0-win32-x86\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.8/cmake-3.8.0-win32-x86.zip'
        7z x -y cmake-3.8.0-win32-x86.zip -oC:\
      }
      $env:PATH="C:\cmake-3.8.0-win32-x86\bin;$env:PATH"
  - ps: |
      if (![IO.File]::Exists("C:\w_mkl_2018.0.124.exe")) {
        ECHO 'w_mkl_2018.0.124.exe does not exist. Preparing to install MKL ..'
        Start-FileDownload 'http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/12079/w_mkl_2018.0.124.exe' -FileName 'C:\w_mkl_2018.0.124.exe'
        C:\w_mkl_2018.0.124.exe -s -l c:\logs\extract-mkl.log -a install --eula=accept --components=all --output='C:\logs\install-mkl-output.txt' --installdir='C:\Program Files (x86)\IntelSWTools' --log='c:\logs\install-mkl.log' | Out-Null
        ECHO 'Done'
      }
      else{
        ECHO 'w_mkl_2018.0.124.exe already existed'
      }


before_build:
  - ps: |
      if ([IO.File]::Exists("C:\logs\install-mkl-output.txt")) {
        ECHO 'Checking if MKL installation end up (and successfully)'
        TYPE C:\logs\install-mkl-output.txt
      }
      else{
        ECHO 'install-mkl-output.txt is not written yet'
        SLEEP 60
      }
  - ps: |
      if ([IO.File]::Exists("C:\logs\install-mkl-output.txt")) {
        ECHO 'Checking if MKL installation end up (and successfully)'
        TYPE C:\logs\install-mkl-output.txt
      }
      else{
        ECHO 'install-mkl-output.txt is not written yet'
        SLEEP 60
      }
  - ps: |
      mkdir build
      cd build
      if ("$env:APPVEYOR_JOB_NAME" -match "Image: Visual Studio 2015") {
          $env:generator="Visual Studio 14 2015"
      } else {
          $env:generator="Visual Studio 15 2017"
      }
      if ($env:PLATFORM -eq "x64") {
          $env:generator="$env:generator Win64"
      }
      echo generator="$env:generator"
      cmake .. -G "$env:generator" -DBLA_VENDOR=Intel

build_script:
  - cmake --build . --config %CONFIGURATION% -- /m /v:minimal

test_script:

deploy: off

artifacts:
  - path: C:\logs\extract-mkl.log
    name: extract-mkl.log

  - path: C:\install-mkl-output.txt
    name: install-mkl-output.txt

  - path: c:\logs\install-mkl.log
    name: install-mkl.log

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
